CManager.Web/Controllers/ChatController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CManager.Core.Entity.AuthenticationModels;
using CManager.Core.Interfaces.Services;
using CManager.Web.Socket;
using CManager.Business.Utilities;

namespace CManager.Web.Controllers
{
    public class ChatController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly IMessageService _messageService;
        private readonly IAttachmentsService _attachmentsService;
        private readonly IWebHostEnvironment _env;
        private readonly IHubContext<NotificationHub> _notificationHubContext;
        private Utilities _util;
        private UserManager<User> _userManager { get; }

        public ChatController(ICourseService courseService, IWebHostEnvironment env,
            IAttachmentsService attachmentsService,
            IHubContext<NotificationHub> notificationHubContext,
            UserManager<User> userManager,
            IConfiguration configuration,
            IMessageService messageService)
        { 
            _courseService = courseService;
            _attachmentsService = attachmentsService;
            _env = env;
            _notificationHubContext = notificationHubContext;
            _userManager = userManager;
            _messageService = messageService;
            _util = new Utilities(configuration.GetConnectionString("DefaultConnection"));
        }
        public async Task<IActionResult> Index()
        {
            return View(await _messageService.GetMessage());
        }
    }
}

CManager.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Transactions;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using CManager.Core.Entity.AuthenticationModels;
using CManager.Web.DbContext;
using CManager.Web.Enums;
using CManager.Web.Models.ViewModels;
using CManager.Core.Interfaces.Services;

namespace CManager.Web.Controllers
{
    public class UserController : Controller
    {
        private UserManager<User> _userManager { get; }
        private SignInManager<User> _signInManager { get; }
        private RoleManager<Role> _roleManager { get; }
        private IRoleService _roleService;

        public UserController(UserManager<User> userManager,
            SignInManager<User> signInManager,
            RoleManager<Role> roleManager,
            IRoleService roleService)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _roleService = roleService;
        }
        // GET: UserController
        public ActionResult SignUp()
        {
            #region Dropdown
            List<Role> identityRoles = new List<Role>()
            {
                new Role(){
                    Name = RoleEnum.Staff.ToString()
                },
                new Role(){
                    Name = RoleEnum.Student.ToString()
                }
            };
            ViewBag.roleList = new SelectList(identityRoles, "Name", "Name");
            #endregion 
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> SignUp(UserViewModel userViewModel)
        {
            #region Dropdown
            List<Role> identityRoles = new List<Role>()
            {
                new Role(){
                    Name = RoleEnum.Staff.ToString()
                },
                new Role(){
                    Name = RoleEnum.Student.ToString()
                }
            };
            ViewBag.roleList = new SelectList(identityRoles, "Name", "Name");
            #endregion
            User newUser = new User { Id = Guid.NewGuid(), Email = userViewModel.Email, UserName = userViewModel.UserName };

            try
            {
                #region Here we'll find if the role is created if not the we'll create the role
                var role = await _roleManager.FindByNameAsync(userViewModel.RoleId); //here role id is used to carry role name//_context.Roles.Where(x=> x.Name == userViewModel.RoleId).SingleOrDefault();
                if (role == null)
                {
                    Role newRole = new Role();
                    newRole.Name = userViewModel.RoleId; //here role id is used to carry role name
                    try
                    {
                        await _roleService.AddAsync(newRole);
                        //await _roleManager.CreateAsync(newRole);
                    }
                    catch (Exception e)
                    {

                    }

                    role = newRole;
                }
                #endregion
                var result = await _userManager.CreateAsync(newUser, userViewModel.Password);
                if (result.Succeeded)
                {
                    var user = await _userManager.FindByIdAsync(newUser.Id.ToString());
                    var resultForRole = await _userManager.AddToRoleAsync(user, role.Name);
                    if (resultForRole.Succeeded)
                    {
                        ViewBag.Message = "Registered Successfully!!!";

                        return View();
                    }
                    else
                    {
                        if (resultForRole.Errors.ToList().Count() != 0)
                        {
                            ViewBag.Message = Helper.Helper.GetErrorList(resultForRole);
                            return View();
                        }
                        else
                        {
                            ViewBag.Message = "Error occoured!!!";
                            return View();
                        }
                    }
                }
                else
                {
                    if (result.Errors.ToList().Count() != 0)
                    {
                        ViewBag.Message = Helper.Helper.GetErrorList(result); ;
                        return View();
                    }
                    else
                    {
                        ViewBag.Message = "Error occoured!!!";
                        return View();
                    }
                }
            }
            catch (Exception e)
            {
                ViewBag.Message = "Error occoured!!!";
                return View();
            }
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Login(UserViewModel userViewModel)
        {
            var user = await _userManager.FindByNameAsync(userViewModel.UsernameOrEmail) ?? await _userManager.FindByEmailAsync(userViewModel.UsernameOrEmail);
            if (user == null)
            {
                ViewBag.Message = "No user found with this username/email.";
                return View();
            }
            try
            {
                var result = await _signInManager.PasswordSignInAsync(user, userViewModel.Password, false, true);
                if (result.Succeeded)
                {
                    //as each user can have only one role, so we can take single
                    var role = (await _userManager.GetRolesAsync(user)).Single();
                    #region
                    var claims = new List<Claim>
                        {
                          new Claim(ClaimTypes.Name, user.UserName),
                          new Claim(ClaimTypes.Email, user.Email),
                          new Claim(ClaimTypes.Role, role)
                        };

                    var claimsIdentity = new ClaimsIdentity(
                      claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var authProperties = new AuthenticationProperties();

                    await HttpContext.SignInAsync(
                      CookieAuthenticationDefaults.AuthenticationScheme,
                      new ClaimsPrincipal(claimsIdentity),
                      authProperties);
                    #endregion
                    if (role == RoleEnum.Staff.ToString())
                        return RedirectToAction("Index", "Staff");
                    else
                        return RedirectToAction("Index", "Student");
                }
                else
                {
                    ViewBag.Message = "Please enter correct password.";
                    return View();
                }

            }
            catch (Exception e)
            {
                ViewBag.Message = "Error occoured!!";
                return View();
                throw e;
            }
        }
        [HttpGet]
        public async Task<ActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            await HttpContext.SignOutAsync("Cookies");
            return RedirectToAction("Index", "Home");
        }
    }
}

CManager.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims;
@inject SignInManager<CManager.Core.Entity.AuthenticationModels.User> SignInManager
@inject UserManager<CManager.Core.Entity.AuthenticationModels.User> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/tostr/toastr.css" rel="stylesheet" />
    <style>
        .alert {
            text-align: center;
        }

        textarea {
            width: 100%;
        }

        .cUL {
            height: 200px;
            width: 100%;
        }

        .cUL {
            overflow: hidden;
            overflow-y: scroll;
        }

        .listformsg {
            border: 1px solid black;
            padding-right: 0px;
            padding-left: 28px;
            width: 50px;
            border-radius: 5px;
        }
        /* Button used to open the chat form - fixed at the bottom of the page */
        .open-button {
            background-color: #555;
            color: white;
            padding: 16px 20px;
            border: none;
            cursor: pointer;
            opacity: 0.8;
            position: fixed;
            bottom: 23px;
            right: 28px;
            width: 280px;
        }

        /* The popup chat - hidden by default */
        .chat-popup {
            display: none;
            position: fixed;
            bottom: 0;
            right: 15px;
            border: 3px solid #f1f1f1;
            z-index: 9;
        }

        /* Add styles to the form container */
        .form-container {
            max-width: 300px;
            padding: 10px;
            background-color: white;
        }

            /* Full-width textarea */
            .form-container textarea {
                width: 100%;
                padding: 15px;
                margin: 5px 0 22px 0;
                border: none;
                background: #f1f1f1;
                /*resize: none;
                min-height: 200px;*/
            }

                /* When the textarea gets focus, do something */
                .form-container textarea:focus {
                    background-color: #ddd;
                    outline: none;
                }

            /* Set a style for the submit/send button */
            .form-container .btn {
                background-color: #4CAF50;
                color: white;
                padding: 16px 20px;
                border: none;
                cursor: pointer;
                width: 100%;
                margin-bottom: 10px;
                opacity: 0.8;
            }

            /* Add a red background color to the cancel button */
            .form-container .cancel {
                background-color: red;
            }

            /* Add some hover effects to buttons */
            .form-container .btn:hover, .open-button:hover {
                opacity: 1;
            }
    </style>
</head>

<body>
    <header>
        @await Component.InvokeAsync("NToastNotify")
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CManager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        @if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.FindByNameAsync(User.Identity.Name).Result, CManager.Web.Enums.RoleEnum.Staff.ToString()))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="AddCourse">Add Course</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="CoursesCreatedByCurrentUser">Created Courses</a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.FindByNameAsync(User.Identity.Name).Result, CManager.Web.Enums.RoleEnum.Student.ToString()))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="SavedCourses">Saved Courses</a>
                            </li>
                            @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Chat" asp-action="Index">Chat List</a>
                            </li>*@
                        }

                    </ul>
                </div>
                <ul class="navbar-nav">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" title="Manage">Hello @User.Identity.Name!</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Logout" asp-controller="User">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="SignUp" asp-controller="User">SignUp</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Login" asp-controller="User">Login</a>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            @if (SignInManager.IsSignedIn(User))
            {
                <button class="open-button" onclick="openForm()">Chat</button>
                <div class="chat-popup" id="myForm">
                    <section class="form-container">
                        <h1>Chat</h1>

                        <label for="msg"><b>Message</b></label>
                        <textarea id="messageTxt" name="messageTxt" placeholder="Type message..">
                        </textarea>
                        <div class="col-md-12">
                            <ul class="cUL" id="cUL" name="cUL">
                                <li></li>
                            </ul>
                        </div>
                        @if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.FindByNameAsync(User.Identity.Name).Result, CManager.Web.Enums.RoleEnum.Staff.ToString()))
                        {
                            <button type="button" id="sendButton" name="sendButton" class="btn">Send</button>
                        }
                        <button type="button" class="btn cancel" onclick="closeForm()">Close</button>
                    </section>
                </div>
            }
        </main>

    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2020 - CManager - <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/tostr/toastr.min.js"></script>
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/noti.js"></script>
    @RenderSection("Scripts", required: false)
    <script>
        function openForm() {
            document.getElementById("myForm").style.display = "block";
        }

        function closeForm() {
            document.getElementById("myForm").style.display = "none";
        }
    </script>
</body>
</html>